import HDCPage from '../pages/hdc'
import NewFormPage from '../pages/newForm'
import Page from '../pages/page'

context('Sign In', () => {
  beforeEach(() => {
    cy.task('reset')
    cy.task('stubSignIn')
  })

  it('Should go to identity numbers section page', () => {
    cy.signIn()
    cy.visit('/newForm')
    const newformPage = Page.verifyOnPage(NewFormPage)
    cy.get('[value=HDC]').check()
    newformPage.nextButton().click()
    const hdcPage = Page.verifyOnPage(HDCPage)
    hdcPage.startButton().click()
    cy.get('a:contains("Identity numbers")').click()
    cy.get('h1').contains('Identity numbers questions').should('exist')
    cy.get('.govuk-summary-list').should('exist')
    cy.get('.govuk-summary-list__key').contains('Nomis ID').should('exist')
    cy.get('.govuk-summary-list__key').contains('PND ID').should('exist')
    cy.get('a:contains("Change")').should('have.length', 2)
  })

  it('Should go to Nomis ID question Page', () => {
    cy.signIn()
    cy.visit('/newForm')
    const newformPage = Page.verifyOnPage(NewFormPage)
    cy.get('[value=HDC]').check()
    newformPage.nextButton().click()
    const hdcPage = Page.verifyOnPage(HDCPage)
    hdcPage.startButton().click()
    cy.get('a:contains("Identity numbers")').click()
    cy.get('[href="/section/identitynumbers/question/nomisId"]').click()
    cy.get('h1').contains('Identity Numbers').should('exist')
    cy.get('label').contains('National offender management information system (NOMIS ID)').should('exist')
    cy.get('#input-nomisId').should('exist')
    cy.get('button:contains("Next")').should('exist')
  })

  it('Should show error if nomis id is empty', () => {
    cy.signIn()
    cy.visit('/newForm')
    const newformPage = Page.verifyOnPage(NewFormPage)
    cy.get('[value=HDC]').check()
    newformPage.nextButton().click()
    const hdcPage = Page.verifyOnPage(HDCPage)
    hdcPage.startButton().click()
    cy.get('a:contains("Identity numbers")').click()
    cy.get('[href="/section/identitynumbers/question/nomisId"]').click()
    cy.get('h1').contains('Identity Numbers').should('exist')
    cy.get('label').contains('National offender management information system (NOMIS ID)').should('exist')
    cy.get('#input-nomisId').should('exist')
    cy.get('button:contains("Next")').click()
    cy.get('#input-nomisId-error').contains('Nomis ID must not be empty').should('exist')
  })

  it('Should go to PND ID page if nomis id is valid', () => {
    cy.signIn()
    cy.visit('/newForm')
    const newformPage = Page.verifyOnPage(NewFormPage)
    cy.get('[value=HDC]').check()
    newformPage.nextButton().click()
    const hdcPage = Page.verifyOnPage(HDCPage)
    hdcPage.startButton().click()
    cy.get('a:contains("Identity numbers")').click()
    cy.get('[href="/section/identitynumbers/question/nomisId"]').click()
    cy.get('h1').contains('Identity Numbers').should('exist')
    cy.get('label').contains('National offender management information system (NOMIS ID)').should('exist')
    cy.get('#input-nomisId').should('exist')
    cy.get('#input-nomisId').type('abc')
    cy.get('button:contains("Next")').click()
    cy.get('label').contains('Police national database (PND ID)').should('exist')
    cy.get('#input-pndId').should('exist')
  })

  it('Should go to Nomis ID question Page', () => {
    cy.signIn()
    cy.visit('/newForm')
    const newformPage = Page.verifyOnPage(NewFormPage)
    cy.get('[value=HDC]').check()
    newformPage.nextButton().click()
    const hdcPage = Page.verifyOnPage(HDCPage)
    hdcPage.startButton().click()
    cy.get('a:contains("Identity numbers")').click()
    cy.get('[href="/section/identitynumbers/question/pndId"]').click()
    cy.get('h1').contains('Identity Numbers').should('exist')
    cy.get('label').contains('Police national database (PND ID)').should('exist')
    cy.get('#input-pndId').should('exist')
    cy.get('button:contains("Next")').should('exist')
  })

  it('Should show error if pnd id is empty', () => {
    cy.signIn()
    cy.visit('/newForm')
    const newformPage = Page.verifyOnPage(NewFormPage)
    cy.get('[value=HDC]').check()
    newformPage.nextButton().click()
    const hdcPage = Page.verifyOnPage(HDCPage)
    hdcPage.startButton().click()
    cy.get('a:contains("Identity numbers")').click()
    cy.get('[href="/section/identitynumbers/question/pndId"]').click()
    cy.get('#input-pndId').should('exist')
    cy.get('button:contains("Next")').click()
    cy.get('#input-pndId-error').contains('PND ID must not be empty').should('exist')
  })

  it('Should go through all questions and redirect back to the section page with value populated', () => {
    cy.signIn()
    cy.visit('/newForm')
    const newformPage = Page.verifyOnPage(NewFormPage)
    cy.get('[value=HDC]').check()
    newformPage.nextButton().click()
    const hdcPage = Page.verifyOnPage(HDCPage)
    hdcPage.startButton().click()
    cy.get('a:contains("Identity numbers")').click()
    cy.get('[href="/section/identitynumbers/question/nomisId"]').click()
    cy.get('#input-nomisId').should('exist')
    cy.get('#input-nomisId').type('mockNomisId')
    cy.get('button:contains("Next")').click()
    cy.get('label').contains('Police national database (PND ID)').should('exist')
    cy.get('#input-pndId').type('mockPndId')
    cy.get('button:contains("Next")').click()

    cy.get('h1').contains('Identity numbers questions').should('exist')
    cy.get('.govuk-summary-list').should('exist')
    cy.get('.govuk-summary-list__key').contains('Nomis ID').should('exist')
    cy.get('.govuk-summary-list__value').contains('mockNomisId').should('exist')
    cy.get('.govuk-summary-list__key').contains('PND ID').should('exist')
    cy.get('.govuk-summary-list__value').contains('mockPndId').should('exist')
  })
})
