const magistratesCourts: Record<string, string> = {
  BARKINGSIDE_MAGISTRATES_COURT: 'Barkingside Magistrates Court',
  BARROW_IN_FURNESS_MAGISTRATES_COURT: 'Barrow-in-Furness Magistrates Court',
  BASILDON_MAGISTRATES_COURT: 'Basildon Magistrates Court',
  BASINGSTOKE_MAGISTRATES_COURT: 'Basingstoke Magistrates Court',
  BELMARSH_MAGISTRATES_COURT: 'Belmarsh Magistrates Court',
  BERWICK_UPON_TWEED_MAGISTRATES_COURT: 'Berwick upon Tweed Magistrates Court',
  BEVERLEY_MAGISTRATES_COURT: 'Beverley Magistrates Court',
  BEXLEY_MAGISTRATES_COURT: 'Bexley Magistrates Court',
  BIRMINGHAM_MAGISTRATES_COURT: 'Birmingham Magistrates Court',
  BLACKBURN_MAGISTRATES_COURT: 'Blackburn Magistrates Court',
  BOLTON_MAGISTRATES_COURT: 'Bolton Magistrates Court',
  BOSTON_MAGISTRATES_COURT: 'Boston Magistrates Court',
  BRADFORD_AND_KEIGHLEY_MAGISTRATES_COURT: 'Bradford and Keighley Magistrates Court',
  BRIDLINGTON_MAGISTRATES_COURT: 'Bridlington Magistrates Court',
  BRIGHTON_MAGISTRATES_COURT: 'Brighton Magistrates Court',
  BRISTOL_MAGISTRATES_COURT: 'Bristol Magistrates Court',
  BROMLEY_MAGISTRATES_COURT: 'Bromley Magistrates Court',
  BURNLEY_MAGISTRATES_COURT: 'Burnley Magistrates Court',
  CAMBRIDGE_MAGISTRATES_COURT: 'Cambridge Magistrates Court',
  CANNOCK_MAGISTRATES_COURT: 'Cannock Magistrates Court',
  CANTERBURY_MAGISTRATES_COURT: 'Canterbury Magistrates Court',
  CARDIFF_MAGISTRATES_COURT: 'Cardiff Magistrates Court',
  CARLISLE_MAGISTRATES_COURT: 'Carlisle Magistrates Court',
  CHELMSFORD_MAGISTRATES_COURT: 'Chelmsford Magistrates Court',
  CHELTENHAM_MAGISTRATES_COURT: 'Cheltenham Magistrates Court',
  CHESTER_MAGISTRATES_COURT: 'Chester Magistrates Court',
  CITY_OF_LONDON_MAGISTRATES_COURT: 'City of London Magistrates Court',
  COLCHESTER_MAGISTRATES_COURT: 'Colchester Magistrates Court',
  COVENTRY_MAGISTRATES_COURT: 'Coventry Magistrates Court',
  CRAWLEY_MAGISTRATES_COURT: 'Crawley Magistrates Court',
  CREWE_SOUTH_CHESHIRE_MAGISTRATES_COURT: 'Crewe (South Cheshire) Magistrates Court',
  CROYDON_MAGISTRATES_COURT: 'Croydon Magistrates Court',
  CWMBRAN_MAGISTRATES_COURT: 'Cwmbran Magistrates Court',
  DARLINGTON_MAGISTRATES_COURT: 'Darlington Magistrates Court',
  DERBY_MAGISTRATES_COURT: 'Derby Magistrates Court',
  DUDLEY_MAGISTRATES_COURT: 'Dudley Magistrates Court',
  EALING_MAGISTRATES_COURT: 'Ealing Magistrates Court',
  EAST_BERKSHIRE_MAGISTRATES_COURT_SLOUGH: 'East Berkshire Magistrates Court, Slough',
  FOLKESTONE_MAGISTRATES_COURT: 'Folkestone Magistrates Court',
  GATESHEAD_MAGISTRATES_COURT: 'Gateshead Magistrates Court',
  GREAT_YARMOUTH_MAGISTRATES_COURT: 'Great Yarmouth Magistrates Court',
  GRIMSBY_MAGISTRATES_COURT: 'Grimsby Magistrates Court',
  GUILDFORD_MAGISTRATES_COURT: 'Guildford Magistrates Court',
  HASTINGS_MAGISTRATES_COURT: 'Hastings Magistrates Court',
  HATFIELD_MAGISTRATES_COURT: 'Hatfield Magistrates Court',
  HAVERFORDWEST_MAGISTRATES_COURT: 'Haverfordwest Magistrates Court',
  HENDON_MAGISTRATES_COURT: 'Hendon Magistrates Court',
  HIGH_WYCOMBE_MAGISTRATES_COURT: 'High Wycombe Magistrates Court',
  HIGHBURY_CORNER_MAGISTRATES_COURT: 'Highbury Corner Magistrates Court',
  HORSHAM_MAGISTRATES_COURT: 'Horsham Magistrates Court',
  HULL_AND_HOLDERNESS_MAGISTRATES_COURT: 'Hull and Holderness Magistrates Court',
  IPSWICH_MAGISTRATES_COURT: 'Ipswich Magistrates Court',
  KIDDERMINSTER_MAGISTRATES_COURT: 'Kidderminster Magistrates Court',
  KINGS_LYNN_MAGISTRATES_COURT: 'Kings Lynn Magistrates Court',
  KIRKLEES_HUDDERSFIELD_MAGISTRATES_COURT: 'Kirklees (Huddersfield) Magistrates Court',
  LAVENDER_HILL_MAGISTRATES_COURT: 'Lavender Hill Magistrates Court',
  LEAMINGTON_SPA_MAGISTRATES_COURT: 'Leamington Spa Magistrates Court',
  LEEDS_MAGISTRATES_COURT: 'Leeds Magistrates Court',
  LEICESTER_MAGISTRATES_COURT: 'Leicester Magistrates Court',
  LINCOLN_MAGISTRATES_COURT: 'Lincoln Magistrates Court',
  LIVERPOOL_KNOWSLEY_MAGISTRATES_COURT: 'Liverpool & Knowsley Magistrates Court',
  LLANDUDNO_MAGISTRATES_COURT: 'Llandudno Magistrates Court',
  LUTON_AND_SOUTH_BEDFORDSHIRE_MAGISTRATES_COURT: 'Luton and South Bedfordshire Magistrates Court',
  MAIDSTONE_MAGISTRATES_COURT: 'Maidstone Magistrates Court',
  MANCHESTER_MAGISTRATES_COURT: 'Manchester Magistrates Court',
  MARGATE_MAGISTRATES_COURT: 'Margate Magistrates Court',
  MEDWAY_MAGISTRATES_COURT: 'Medway Magistrates Court',
  MILTON_KEYNES_MAGISTRATES_COURT: 'Milton Keynes Magistrates Court',
  NEWCASTLE_UPON_TYNE_MAGISTRATES_COURT: 'Newcastle upon Tyne Magistrates Court',
  NEWPORT_SOUTH_WALES_MAGISTRATES_COURT: 'Newport (South Wales) Magistrates Court',
  NEWTON_ABBOT_MAGISTRATES_COURT: 'Newton Abbot Magistrates Court',
  NEWTON_AYCLIFFE_MAGISTRATES_COURT: 'Newton Aycliffe Magistrates Court',
  NORTH_SOMERSET_MAGISTRATES_COURT: 'North Somerset Magistrates Court',
  NORTH_TYNESIDE_MAGISTRATES_COURT: 'North Tyneside Magistrates Court',
  NORTHAMPTON_MAGISTRATES_COURT: 'Northampton Magistrates Court',
  NORWICH_MAGISTRATES_COURT: 'Norwich Magistrates Court',
  NOTTINGHAM_MAGISTRATES_COURT: 'Nottingham Magistrates Court',
  NUNEATON_MAGISTRATES_COURT: 'Nuneaton Magistrates Court',
  OXFORD_MAGISTRATES_COURT: 'Oxford Magistrates Court',
  PETERBOROUGH_MAGISTRATES_COURT: 'Peterborough Magistrates Court',
  PETERLEE_MAGISTRATES_COURT: 'Peterlee Magistrates Court',
  PLYMOUTH_MAGISTRATES_COURT: 'Plymouth Magistrates Court',
  POOLE_MAGISTRATES_COURT: 'Poole Magistrates Court',
  PORTSMOUTH_MAGISTRATES_COURT: 'Portsmouth Magistrates Court',
  PRESTON_MAGISTRATES_COURT: 'Preston Magistrates Court',
  READING_MAGISTRATES_COURT: 'Reading Magistrates Court',
  REDDITCH_MAGISTRATES_COURT: 'Redditch Magistrates Court',
  ROMFORD_MAGISTRATES_COURT: 'Romford Magistrates Court',
  SEFTON_MAGISTRATES_COURT: 'Sefton Magistrates Court',
  SEVENOAKS_MAGISTRATES_COURT: 'Sevenoaks Magistrates Court',
  SHEFFIELD_MAGISTRATES_COURT: 'Sheffield Magistrates Court',
  SKIPTON_MAGISTRATES_COURT: 'Skipton Magistrates Court',
  SOUTH_TYNESIDE_MAGISTRATES_COURT: 'South Tyneside Magistrates Court',
  SOUTHEND_MAGISTRATES_COURT: 'Southend Magistrates Court',
  ST_ALBANS_MAGISTRATES_COURT: 'St Albans Magistrates Court',
  STAINES_MAGISTRATES_COURT: 'Staines Magistrates Court',
  STEVENAGE_MAGISTRATES_COURT: 'Stevenage Magistrates Court',
  STOCKPORT_MAGISTRATES_COURT: 'Stockport Magistrates Court',
  STRATFORD_MAGISTRATES_COURT: 'Stratford Magistrates Court',
  SWANSEA_MAGISTRATES_COURT: 'Swansea Magistrates Court',
  SWINDON_MAGISTRATES_COURT: 'Swindon Magistrates Court',
  TAMESIDE_MAGISTRATES_COURT: 'Tameside Magistrates Court',
  TAUNTON_MAGISTRATES_COURT: 'Taunton Magistrates Court',
  TEESSIDE_MAGISTRATES_COURT: 'Teesside Magistrates Court',
  TELFORD_MAGISTRATES_COURT: 'Telford Magistrates Court',
  THAMES_MAGISTRATES_COURT: 'Thames Magistrates Court',
  TRURO_MAGISTRATES_COURT: 'Truro Magistrates Court',
  UXBRIDGE_MAGISTRATES_COURT: 'Uxbridge Magistrates Court',
  WALSALL_MAGISTRATES_COURT: 'Walsall Magistrates Court',
  WARRINGTON_MAGISTRATES_COURT: 'Warrington Magistrates Court',
  WELLINGBOROUGH_MAGISTRATES_COURT: 'Wellingborough Magistrates Court',
  WELSHPOOL_MAGISTRATES_COURT: 'Welshpool Magistrates Court',
  WEST_HAMPSHIRE_MAGISTRATES_COURT: 'West Hampshire Magistrates Court',
  WESTMINSTER_MAGISTRATES_COURT: 'Westminster Magistrates Court',
  WIGAN_AND_LEIGH_MAGISTRATES_COURT: 'Wigan and Leigh Magistrates Court',
  WILLESDEN_MAGISTRATES_COURT: 'Willesden Magistrates Court',
  WIMBLEDON_MAGISTRATES_COURT: 'Wimbledon Magistrates Court',
  WIRRAL_MAGISTRATES_COURT: 'Wirral Magistrates Court',
  WOLVERHAMPTON_MAGISTRATES_COURT: 'Wolverhampton Magistrates Court',
  WORTHIN_MAGISTRATE_COURT: 'Worthing Magistrates Court',
  WREXHAM_MAGISTRATES_COURT: 'Wrexham Magistrates Court',
  YEOVIL_COUNTY_MAGISTRATES_COURT: 'Yeovil County, Magistrates Court',
}

export default magistratesCourts
