const prisons: Record<string, string> = {
  ALTCOURSE_PRISON: 'Altcourse Prison',
  ASHFIELD_PRISON: 'Ashfield Prison',
  ASKHAM_GRANGE_PRISON_AND_YOUNG_OFFENDER_INSTITUTION: 'Askham Grange Prison and Young Offender Institution',
  AYLESBURY_PRISON_AND_YOUNG_OFFENDER_INSTITUTION: 'Aylesbury Prison and Young Offender Institution',
  BEDFORD_PRISON: 'Bedford Prison',
  BELMARSH_PRISON: 'Belmarsh Prison',
  BERWYN_PRISON: 'Berwyn Prison',
  BIRMINGHAM_PRISON: 'Birmingham Prison',
  BRINSFORD_PRISON: 'Brinsford Prison',
  BRISTOL_PRISON: 'Bristol Prison',
  BRIXTON_PRISON: 'Brixton Prison',
  BRONZEFIELD_PRISON: 'Bronzefield Prison',
  BUCKLEY_HALL_PRISON: 'Buckley Hall Prison',
  BULLINGDON_PRISON: 'Bullingdon Prison',
  BURE_PRISON: 'Bure Prison',
  CARDIFF_PRISON: 'Cardiff Prison',
  CHANNINGS_WOOD_PRISON: 'Channings Wood Prison',
  CHELMSFORD_PRISON: 'Chelmsford Prison',
  COLDINGLEY_PRISON: 'Coldingley Prison',
  COOKHAM_WOOD_YOUNG_OFFENDER_INSTITUTION: 'Cookham Wood Young Offender Institution',
  DARTMOOR_PRISON: 'Dartmoor Prison',
  DEERBOLT_PRISON: 'Deerbolt Prison',
  DONCASTER_PRISON: 'Doncaster Prison',
  DOVEGATE_PRISON: 'Dovegate Prison',
  DOWNVIEW_PRISON_AND_YOUNG_OFFENDER_INSTITUTION: 'Downview Prison and Young Offender Institution',
  DRAKE_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION: 'Drake Hall Prison and Young Offender Institution',
  DURHAM_PRISON: 'Durham Prison',
  EAST_SUTTON_PARK_PRISON_AND_YOUNG_OFFENDERS_INSTITUTION: 'East Sutton Park Prison and Young Offender Institution',
  EASTWOOD_PARK_PRISON_AND_YOUNG_OFFENDER_INSTITUTION: 'Eastwood Park Prison and Young Offender Institution',
  ELMLEY_PRISON: 'Elmley Prison',
  ERLESTOKE_PRISON: 'Erlestoke Prison',
  EXETER_PRISON: 'Exeter Prison',
  FEATHERSTONE_PRISON: 'Featherstone Prison',
  FELTHAM_YOUNG_OFFENDER_INSTITUTION: 'Feltham Young Offender Institution',
  FIVE_WELLS_PRISON: 'Five Wells Prison',
  FORD_PRISON: 'Ford Prison',
  FOREST_BANK_PRISON: 'Forest Bank Prison',
  FOSTON_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION: 'Foston Hall Prison and Young Offender Institution',
  FRANKLAND_PRISON: 'Frankland Prison',
  FULL_SUTTON_PRISON: 'Full Sutton Prison',
  GARTH_PRISON: 'Garth Prison',
  GARTREE_PRISON: 'Gartree Prison',
  GRENDON_PRISON: 'Grendon Prison',
  GUYS_MARSH_PRISON: 'Guys Marsh Prison',
  HATFIELD_PRISON: 'Hatfield Prison',
  HAVERIGG_PRISON: 'Haverigg Prison',
  HEWELL_PRISON: 'Hewell Prison',
  HIGH_DOWN_PRISON: 'High Down Prison',
  HIGHPOINT_PRISON: 'Highpoint Prison',
  HINDLEY_PRISON: 'Hindley Prison',
  HOLLESLEY_BAY_PRISON: 'Hollesley Bay Prison',
  HOLME_HOUSE_PRISON: 'Holme House Prison',
  HULL_PRISON: 'Hull Prison',
  HUMBER_PRISON: 'Humber Prison',
  HUNTERCOMBE_PRISON: 'Huntercombe Prison',
  ISIS_PRISON: 'Isis Prison',
  ISLE_OF_WIGHT_PRISON: 'Isle of Wight Prison',
  KIRKHAM_PRISON: 'Kirkham Prison',
  KIRKLEVINGTON_GRANGE_PRISON: 'Kirklevington Grange Prison',
  LANCASTER_FARMS_PRISON: 'Lancaster Farms Prison',
  LEEDS_PRISON: 'Leeds Prison',
  LEICESTER_PRISON: 'Leicester Prison',
  LEWES_PRISON: 'Lewes Prison',
  LEYHILL_PRISON: 'Leyhill Prison',
  LINCOLN_PRISON: 'Lincoln Prison',
  LINDHOLME_PRISON: 'Lindholme Prison',
  LITTLEHEY_PRISON: 'Littlehey Prison',
  LIVERPOOL_PRISON: 'Liverpool Prison',
  LONG_LARTIN_PRISON: 'Long Lartin Prison',
  LOW_NEWTON_PRISON_AND_YOUNG_OFFENDER_INSTITUTION: 'Low Newton Prison and Young Offender Institution',
  LOWDHAM_GRANGE_PRISON: 'Lowdham Grange Prison',
  MAIDSTONE_PRISON: 'Maidstone Prison',
  MANCHESTER_PRISON: 'Manchester Prison',
  MOORLAND_PRISON: 'Moorland Prison',
  MORTON_HALL_PRISON: 'Morton Hall Prison',
  NEW_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION: 'New Hall Prison and Young Offender Institution',
  NORTH_SEA_CAMP_PRISON: 'North Sea Camp Prison',
  NORTHUMBERLAND_PRISON: 'Northumberland Prison',
  NORWICH_PRISON: 'Norwich Prison',
  NOTTINGHAM_PRISON: 'Nottingham Prison',
  OAKWOOD_PRISON: 'Oakwood Prison',
  ONLEY_PRISON: 'Onley Prison',
  PARC_PRISON_AND_YOUNG_OFFENDER_INSTITUTION: 'Parc Prison and Young Offender Institute',
  PENTONVILLE_PRISON: 'Pentonville Prison',
  PETERBOROUGH_PRISON: 'Peterborough Prison',
  PORTLAND_PRISON_AND_YOUNG_OFFENDER_INSTITUTION: 'Portland Prison and Young Offender Institution',
  PRESCOED_PRISON: 'Prescoed Prison',
  PRESTON_PRISON: 'Preston Prison',
  RANBY_PRISON: 'Ranby Prison',
  RISLEY_PRISON: 'Risley Prison',
  ROCHESTER_PRISON: 'Rochester Prison',
  RYE_HILL_PRISON: 'Rye Hill Prison',
  SEND_PRISON: 'Send Prison',
  SPRING_HILL_PRISON: 'Spring Hill Prison',
  STAFFORD_PRISON: 'Stafford Prison',
  STANDFORD_HILL_PRISON: 'Standford Hill Prison',
  STOCKEN_PRISON: 'Stocken Prison',
  STOKE_HEATH_PRISON: 'Stoke Heath Prison',
  STYAL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION: 'Styal Prison and Young Offender Institution',
  SUDBURY_PRISON: 'Sudbury Prison',
  SWALESIDE_PRISON: 'Swaleside Prison',
  SWANSEA_PRISON: 'Swansea Prison',
  SWINFEN_HALL_PRISON: 'Swinfen Hall Prison',
  THAMESIDE_PRISON: 'Thameside Prison',
  THE_MOUNT_PRISON: 'The Mount Prison',
  THE_VERNE_PRISON: 'The Verne Prison',
  THORN_CROSS_PRISON: 'Thorn Cross Prison',
  USK_PRISON: 'Usk Prison',
  WAKEFIELD_PRISON: 'Wakefield Prison',
  WANDSWORTH_PRISON: 'Wandsworth Prison',
  WARREN_HILL_PRISON: 'Warren Hill Prison',
  WAYLAND_PRISON: 'Wayland Prison',
  WEALSTUN_PRISON: 'Wealstun Prison',
  WERRINGTON_YOUNG_OFFENDER_INSTITUTION: 'Werrington Young Offender Institution',
  WETHERBY_YOUNG_OFFENDER_INSTITUTION: 'Wetherby Young Offender Institution',
  WHATTON_PRISON: 'Whatton Prison',
  WHITEMOOR_PRISON: 'Whitemoor Prison',
  WINCHESTER_PRISON: 'Winchester Prison',
  WOODHILL_PRISON: 'Woodhill Prison',
  WORMWOOD_SCRUBS_PRISON: 'Wormwood Scrubs Prison',
  WYMOTT_PRISON: 'Wymott Prison',
}

export default prisons
